# ---------------------------------------------
# | THIS FILE WAS AUTOGENERATED! DO NOT EDIT! |
# ---------------------------------------------
# edit notebooks/27_gru.ipynb and run generate_all.py

import sys
from os.path import join

sys.path.insert(0, '/'.join(sys.path[0].split('/')[:-1] + ['scripts']))
from lstm import *

class GRUCell(nn.Module):
    def __init__(self, i, h):
        '''GRU cell.
            i: input data dimension
            h: number of hidden units in the gru cell
        '''
        super().__init__()
        self.i, self.h = i, h
        self.Wz = nn.Parameter(init_2d_weight((i, h)))
        self.Wr = nn.Parameter(init_2d_weight((i, h)))
        self.Wh = nn.Parameter(init_2d_weight((i, h)))
        self.Uz = nn.Parameter(init_2d_weight((h, h)))
        self.Ur = nn.Parameter(init_2d_weight((h, h)))
        self.Uh = nn.Parameter(init_2d_weight((h, h)))
        self.bz = nn.Parameter(torch.zeros(h))
        self.br = nn.Parameter(torch.zeros(h))

    def forward(self, x, h):
        z =   (x @ self.Wz + h @ self.Uz).sigmoid()
        r =   (x @ self.Wr + h @ self.Ur).sigmoid()
        h_t = (x @ self.Wh + r * h @ self.Uh).tanh()
        h = weighted_sum(h, h_t, z)
        return h

class GRULayer(nn.Module):
    def __init__(self, i, h):
        '''Wrapper for passing different input timestamps into GRU cell
            i: input data dimension
            h: number of hidden units in the lstm cell
        '''
        super().__init__()
        self.cell = GRUCell(i, h)

    def forward(self, inps, h):
        outputs = []
        for inp in inps.unbind(1):
            h = self.cell(inp, h)
            outputs.append(h)
        return torch.stack(outputs, 1), h