# ---------------------------------------------
# | THIS FILE WAS AUTOGENERATED! DO NOT EDIT! |
# ---------------------------------------------
# edit notebooks/21_progress_bar.ipynb and run generate_all.py

import sys
sys.path.insert(0, '/'.join(sys.path[0].split('/')[:-1] + ['scripts']))

from fastprogress import master_bar, progress_bar
from fastprogress.fastprogress import format_time
from early_stopping import *

class ProgressViewer(Callback):
    '''Callback utilizing FastAI frontend lib to display neat looking training progress'''
    def before_fit(self):
        self.mbar = master_bar(range(self.num_epochs))
        self.mbar.on_iter_begin()
        self.learner.logger = partial(self.mbar.write, table=True)

    def after_fit(self):
        self.mbar.on_iter_end()

    def after_batch(self):
        self.pb.update(self.iters_count)

    def set_pb(self, data_loader):
        self.pb = progress_bar(data_loader, parent=self.mbar)
        self.mbar.update(self.epoch)

    def before_epoch(self):
        self.set_pb(self.data_bunch.train_dl)

    def before_valid(self):
        self.set_pb(self.data_bunch.valid_dl)